trigger: none
pool:
  vmImage: ubuntu-latest

parameters:
- name: env
  displayName: Environment
  type: string
  default: "r2dev"
  values:
  - r2dev
  - r2sit
  - r2uat
  - r2train
  - prod

variables:
- name: serviceConnection
  ${{ if in(parameters.env, 'r2dev') }}:
    value: AwsDev
  ${{ elseif in(parameters.env, 'r2sit', 'r2uat', 'r2train') }}:
    value: AwsNonProd
  ${{ elseif in(parameters.env, 'prod') }}:
    value: AwsProd
- name: region
  value: ap-southeast-2
- name: ProjPrefix
  value: swmi

stages:
- stage: code_check
  displayName: Code quality check
  jobs:
  - job: code_qual_check
    displayName: Code Valun Check
    variables:
    - group: "AWS_INTEGRATION"
    - name: vsafetyAPIkey
      value: $[variables.safetyAPIkey]
    steps:
    - task: Bash@3
      name: codeQuality
      displayName: Code quality checks
      inputs:
        targetType: filePath
        filePath: $(System.DefaultWorkingDirectory)/python-code-check.sh
        arguments: $(System.DefaultWorkingDirectory)/bandit.yaml $(vsafetyAPIkey)

- stage: ${{parameters.env}}_Build_Deploy
  displayName: Build and Deploy to ${{parameters.env}} Environment
  jobs:
  - job: build
    displayName: Build and Deploy
    continueOnError: true
    steps:
    - task: UsePythonVersion@0
      displayName: "Use Python 3.13"
      inputs:
        versionSpec: "3.13"

    - task: AWSShellScript@1
      displayName: "Build SAM"
      inputs:
        awsCredentials: ${{ variables.serviceConnection }}
        regionName: ${{ variables.region }}
        scriptType: "inline"
        inlineScript: |
          # It replaces the ' AWS ENVIRONMENT' based on the chosen environment during pipeline execution, whether it's 'r2dev,' 'r2sit,' or any other environment. It's important not to remove or modify this line.
          sed -i 's/myenvironment/${{ parameters.env }}/g' template.yaml
          python --version
          sam build --debug --template-file template.yaml

    - task: AWSShellScript@1
      displayName: "Package"
      inputs:
        awsCredentials: ${{ variables.serviceConnection }}
        regionName: ${{ variables.region }}
        scriptType: "inline"
        inlineScript: |
          sam package --s3-bucket $(projPrefix)-${{ parameters.env }}-sourcecode \
          --output-template-file ${{ parameters.env }}_int_c1_packaged.yaml \
          --s3-prefix ${{ parameters.env }}_int_c1_stack --force-upload

    - task: AWSShellScript@1
      displayName: "Deploy Infrastructure"
      inputs:
        awsCredentials: ${{ variables.serviceConnection }}
        regionName: ${{ variables.region }}
        scriptType: "inline"
        inlineScript: |
          sam deploy \
          --template-file ${{ parameters.env }}_int_c1_packaged.yaml \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --capabilities CAPABILITY_IAM  \
          --stack-name seil-${{ parameters.env }}-c1 \
          --s3-bucket $(projPrefix)-${{ parameters.env }}-sourcecode \
          --s3-prefix ${{ parameters.env }}_int-c1_stack

- stage: versionTag
  displayName: Set a git tag with the version number
  jobs:
  - job: Tag
    continueOnError: true
    steps:
    - checkout: self
      persistCredentials: true

    - task: gitversion/setup@0
      displayName: Install GitTools
      inputs:
        versionSpec: "5.x"
        preferLatestVersion: true
        fetchDepth: 0

    - task: gitversion/execute@0
      displayName: Calculate SemVer
      inputs:
        useConfigFile: true
        configFilePath: "./GitVersion.yml"

    - script: echo current version is $(GitVersion.SemVer)
      displayName: "Display calculated version"

    - task: Cmdline@2
      displayName: Init git global config
      inputs:
        script: |
          git config --global user.email "pipelineuser"
          git config --global user.name "CI/CD Pipeline"

    - task: CmdLine@2
      displayName: Create Git Tag for the current version
      inputs:
        script: |
          git tag -a $(GitVersion.SemVer) -m "Tagged version $(GitVersion.SemVer)"
          git push origin $(GitVersion.SemVer)
